Repository tmdwo5825-naver-com/FE, pull requests merged in 2023-05, with the labels that each got.

#36 feature : 마커클릭 시 띄울 오버레이를 생성한다.
  src/companent/ClearModal.jsx
  src/companent/ClearModal.module.css
  src/companent/ExplainBox.jsx
  src/companent/ExplainBox.module.css
  src/companent/MapShowAll.jsx
Labels: feature

#38 refactor : ExplainBox의 디자인을 개선한다.
  src/companent/ExplainBox.jsx
  src/companent/ExplainBox.module.css
  src/companent/MapShowAll.jsx
Labels: refactor

#39 feature: 하단네비게이션 기능을 추가한다.
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/companent/Map.module.css
  src/companent/MapShowAll.jsx
  src/companent/NavigateBar.jsx
  src/companent/NavigateBar.module.css
  src/companent/ToShowAll.jsx
Labels: feature, refactor

#41 feature: 인트로 페이지를 추가한다.
  src/IntroPage.jsx
  src/companent/NavigateBar.jsx
  src/index.jsx
Labels: feature

#43 refacor: 인트로 페이지를 추가한다.
  src/companent/IntroPage.jsx
  src/companent/IntroPage.module.css
  src/companent/image/img.png
  src/companent/routes/RootLayout.jsx
  src/index.jsx
Labels: refactor

#44 Feature/37 circle marker
  src/companent/CircleImage.jsx
  src/companent/ExplainBox.jsx
  src/companent/Map.module.css
  src/companent/MapShowAll.jsx
Labels: feature, refactor

#47 feature : 업로드 기능을 추가한다.
  src/companent/Map.jsx
  src/companent/Map.module.css
  src/companent/NavigateBar.jsx
  src/companent/UploadBox.jsx
Labels: feature

#49 feature : 파일을 받는기능 기능을 추가한다.
  src/companent/Map2.jsx
  src/index.jsx
Labels: feature

#50 refactor : UploadBox의 디자인을 개선한다.
  src/companent/Map.module.css
  src/companent/UploadBox.jsx
  src/companent/UploadBox.module.css
Labels: feature, refactor

#51 refactor : introPage Text 를 수정한다.
  src/companent/IntroPage.jsx
  src/companent/IntroPage.module.css
Labels: refactor

#52 refactor : UploadBox의 Design을 수정한다.
  src/companent/UploadBox.module.css
Labels: refactor

#54 refactor : 업로드 버그 수정한다.
  src/companent/UploadBox.jsx
Labels: bug

#56 feature : 현재 위치로 이동하는 버튼 추가한다.
  src/companent/Map.jsx
  src/companent/Map.module.css
Labels: feature

#58 refactor : 서버로부터 파일을 가져와 마커를 띄우는 기능을 추가한다.
  src/companent/ExplainBox.jsx
  src/companent/Map2.jsx
  src/companent/MapShowAll.jsx
  src/db/data.json
Labels: bug, refactor

#61 feature : CatTower 기능을 개발한다.
  src/companent/Map3Hour.jsx
Labels: feature

#63 bug : 백엔드와 연결이 잘되도록 코드를 수정한다.
  src/companent/ExplainBox.jsx
  src/companent/Map2.jsx
  src/companent/Map3Hour.jsx
  src/db/data2.json
Labels: bug

#64 Refactor/cat tower xy
  src/companent/CircleImage.jsx
  src/companent/Map.module.css
  src/companent/Map3Hour.jsx
  src/companent/NavigateBar.jsx
  src/index.jsx
Labels: refactor

#65 refactor : emoji를 추가한다.
  src/companent/ExplainBox.jsx
  src/companent/ExplainBox.module.css
Labels: refactor

#68 refactor : 인트로페이지 디자인 변경한다
  public/index.html
  public/nyala.ttf
  src/companent/InfoBox.jsx
  src/companent/InfoBox.module.css
  src/companent/IntroPage.jsx
  src/companent/IntroPage.module.css
Labels: refactor

#69 feature : 설명버튼을 추가한다.
  src/companent/InfoBox.jsx
  src/companent/InfoBox.module.css
  src/companent/Map.module.css
  src/companent/Map2.jsx
  src/companent/Map3Hour.jsx
Labels: feature

#71 bug : 캣타워와 백엔드를 연결하는 코드를 수정한다.
  src/companent/InfoBox.module.css
  src/companent/IntroPage.module.css
  src/companent/Map.module.css
  src/companent/Map3Hour.jsx
  src/companent/UploadBox.jsx
Labels: bug

#72 feature : Cat Tower Marker 를 생성한다.
  public/Picture2.png
  public/yang.png
  src/companent/Map.module.css
  src/companent/Map3Hour.jsx
Labels: feature
